### PR TITLE
Add terms and conditions page

### PR DESCRIPTION
**Pull request by tbille**
# Summary

Add terms and conditions page

# QA
- With a new user
- `./run`
- http://0.0.0.0:8004/account
- http://0.0.0.0:8004/account/agreement
- Accept terms and conditions
- Should be redirected to /account page

# Screenshot
screenshot-2018-2-12 developer program agreement linux software in the snap store

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
Not sure about the box, usually you see a window with the full terms and conditions. Here it feels like we're trying to hide them behind a click. Not a blocker, just don't think it's ideal. Adding design +1 as I don't think that's a crucial thing and can be improved later.

**Comment by tbille** [comment]
@lyubomir-popov For now I took the exact same page as we have on dashboard.

**Comment by lyubomir-popov** [comment]
@tbille I assumed that's the case, and have added the design +1 label. My comment was just to indicate that there are enhancements I'd like to propose if / when an opportunity arises.

**Comment by matthewpaulthomas** [comment]
I have no opinion on whether it’s best to improve the design in this PR, or leave it for later. But if it’s best to leave it for later, then it would be quicker not to add “Design needed” in the first place.

If it’s best to improve the design in this PR, then:
- [ ] As Lyubo said, show the terms inline.
- [ ] Decide on one overall heading for the terms, rather than two.
- [ ] Remove the punctuation from the end of the checkbox label.
- [ ] Follow our standard commit button layout: “Sign up” rightmost, “Cancel” left of it.

**Comment by cprov** [comment]
@tbille buid.s.io actually depends on the existing (bad) API behavior, see https://github.com/canonical-websites/build.snapcraft.io/blob/master/src/common/actions/auth-store.js#L246

Instead of changing this in a backward-incompatible way (there is not API versioning support atm), we should probably check the error `message` if code is `user-not-ready`. Moreover, we should really be solving both "problems" at once (accepting the agreement and setting username if necessary).

**Comment by bartaz** [comment]
I got an error when doing QA:

My steps:

- go to http://snapcraft.io-pr-299.run.demo.haus/account
- create new account
- validate email
- accept and log in
- when I got redirected from login to http://snapcraft.io-pr-299.run.demo.haus/account I got a KeyError:

screen shot 2018-02-15 at 09 40 05

**Comment by tbille** [comment]
@bartaz this is going to be fixed in this PR https://github.com/canonical-websites/snapcraft.io/pull/304

**Comment by tbille** [comment]
@matthewpaulthomas 
> As Lyubo said, show the terms inline.

- Do you mean diplaying all the terms and conditions in the page instead of redirecting to ubuntu.com? Because this will mean that we will need to update this page all the time the conditions are changed on ubuntu.com...

> Decide on one overall heading for the terms, rather than two.

- I am open to suggestions :smile: 

@cprov I am now doing the same control as we have in b.s.io

@bartaz Error fixed and merge #304

**Comment by lyubomir-popov** [comment]
Would it be possible to add a couple of rems of padding underneath? On pages taller than the window the buttons touch the footer. Also as @matthewpaulthomas said, the buttons need to be right aligned, green one right-most, cancel to the left. 

image

**Comment by tbille** [comment]
@lyubomir-popov can you hard refresh the page because it seems it is due to the cache

**Comment by lyubomir-popov** [comment]
I did, still see it as above. Ideally this should be like that:

screen shot 2018-02-21 at 14 57 26

**Comment by Lukewh** [comment]
@lyubomir-popov @matthewpaulthomas if you check the latest demo are we ok to land this?

**Comment by lyubomir-popov** [comment]
@tbille not sure if it's cache (tried disabling when devtools is open, didn't help) but I still see the u-align-right and col-4 on the same div, leading to the 4-col div not having a margin-left. Could we at least have this sort of markup so the utility class doesn't interfere with the grid classes?
```
<div class="col-4"><div class="u-align--right">
            <a class="p-button--neutral" href="/">Cancel</a>
            <button class="p-button--positive" disabled="disabled" type="submit">Continue</button>
          </div>
</div>
```

that makes it look like this (still too much white space above, but at leaast aligned on the right):

<div class="col-4"><div class="u-align--right">
            <a class="p-button--neutral" href="/">Cancel</a>
            <button class="p-button--positive" disabled="disabled" type="submit">Continue</button>
          </div>
</div>

**Comment by Lukewh** [comment]
Sorry @lyubomir-popov should be sorted now, if you could try again thanks.

**Comment by matthewpaulthomas** [comment]
Good to see that the rest of the layout fixes have survived. The buttons still aren’t exactly in the right place, but that’s not Budapestworthy.

**Pull request merged**
