### PR TITLE
Header and footer update

### PR DESCRIPTION
**Pull request by Lukewh**
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1157
Supercedes https://github.com/canonical-websites/snapcraft.io/pull/1149

## QA

- Pull branch
- `./run`
- Visit http://0.0.0.0:8004
- Ensure the global-nav and footer looks ok

### CODE REVIEW

**Comment by bartaz** [comment]
@Lukewh @lyubomir-popov Why the border addition?

Ubuntu.com doesn't seem to have a border on global nav, at seems it is not visible.

In here border is barely, but visible, especially when items in main nav are hovered or selected:
screen shot 2018-10-01 at 11 31 35

So it seems like the border color is different from global nav color, different from main nav color, different from main nav hover/select color.

Is this intended?

**Comment by lyubomir-popov** [comment]
@bartaz good spot, I think you're right. What I was trying to do is prevent the merging of selected menu item and top strip. But we did this better on ubuntu.com and should just port it over from there, including the hover state colour.

**Comment by Lukewh** [comment]
@bartaz removed the global-nav border

**Comment by bartaz** [comment]
Looks good. But now it seems like header navigation colours were slightly changed here on snapcraft.io, which again leads to inconsistent navigation styles between snapcraft.io, docs and BSI.

**Comment by lyubomir-popov** [comment]
@Lukewh the only thing I notice is that the top canonical bar is darker on snapcraft than on ubuntu.com

**Pull request merged**
