### PR TITLE
Job link

### PR DESCRIPTION
**Pull request by Lukewh**
Footer link for the jobs page.

Fixes https://github.com/canonicalltd/snap-squad/issues/686

### CODE REVIEW

**Comment by bartaz** [comment]
We really want it this big?

screen shot 2018-09-06 at 15 35 44

**Comment by evandandrea** [comment]
That's the wrong job posting :)

Could we put it in the header instead? I can't imagine many people make it to the bottom of the page.

```<a href="https://boards.greenhouse.io/canonical/jobs/1161820">We're hiring</a>```

**Comment by Lukewh** [comment]
Updated to put in the header and look like the global-nav from https://www.ubuntu.com

screenshot_2018-09-12 snapcraft - snaps are universal linux packages

**Comment by anthonydillon** [comment]
What's going to happen when we add the global nav to snapcraft.io? Interesting idea to add a "We are hiring" link to the global nav so we get the messaging out there across all the sites.

**Comment by therealjuan** [comment]
We might want to change the background-color of the main navigation to #333 to match the ubuntu navigation 👍

**Comment by Lukewh** [comment]
@anthonydillon. @therealjuan and I talked about this and https://github.com/canonical-webteam/global-nav/issues/46 would be a solution.

**Pull request merged**
