### PR TITLE
Show bigger promote button

### LINKED ISSUE #1504: Release UI: Replace ⤴ with Promote
Since a big majority of snaps have less than 3 architectures and the ⤴ character does not explain enough, we can replace it with `Promote…` with an ellipsis (character instead of 3 dots) to indicate a contextual menu will appear with options on which channel to promote to.

image

### PR DESCRIPTION
**Pull request by bartaz**
Fixes #1504

Showing bigger Promote button (with label instead of the icon)

### QA

- ./run or https://snapcraft-io-canonical-websites-pr-1506.run.demo.haus/
- go to Releases page of snap any snap
- promote button should be bigger with "Promote" label instead of the icon

screenshot 2019-01-11 at 15 46 29

### CODE REVIEW

**Comment by therealjuan** [comment]
Would it be possible to remove `...` and make it appear on all snaps regardless of number of archs?

**Comment by bartaz** [comment]
@therealjuan Snaps with 6 architectures already barely fit (with small button). With bigger button there is just not enough space for them:

screenshot 2019-01-11 at 12 22 38

**Comment by therealjuan** [comment]
Works good and looks better. Thanks @bartaz 👍

**Comment by bartaz** [comment]
@Lukewh This part of UI had hardcoded width from the beginning - we are quite tight in space there and we don't want things to move around too much.

**Pull request merged**
