### PR TITLE
Small tidy up for unnecessary hrs on snap pages

### PR DESCRIPTION
**Pull request by Lukewh**
# Done

- Added hr's to conditionals

# Screenshots

## Before
screenshot-2018-5-22 fabulous peesh - linux software in the snap store

## After
screenshot-2018-5-22 fabulous peesh - linux software in the snap store 1

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
Looks good, and as a general rule - hrs separate same-level groups of elements, so there should never be one one above the first or under the last.

In vanilla 1.7.0 we have a %pseudo-hr placeholder, which allows to define these as:
el + el {@extend %pseudo-hr--top;} 

This way, they can never show up in places they are not needed.

**Comment by bartaz** [comment]
Fixes #673

**Comment by bartaz** [comment]
@lyubomir-popov Are things like `%pseudo-hr--top` documented anywhere - or are there plans for it? It seems there are quite significant internal changes to Vanilla in terms of spacing variables and other things. Knowing about them would be very helpful for migration to 1.7.1 that we should do quite soon.

**Comment by lyubomir-popov** [comment]
@bartaz I can see @Caleb-Ellis is doing a lot of work to explain the changes in the docs, and I'm writing an overview as a blog post. Might be quickest to just have a catchup or a workshop to discuss these if there is interest.

**Pull request merged**
