### PR TITLE
Toggle snap privacy on listing page

### PR DESCRIPTION
**Pull request by Lukewh**
# Done

- Added `Private` toggle to listings page with some help text

# QA

- Pull the branch
- `./run`
- Visit http://0.0.0.0:8004/account/snaps/snap_name/listing or http://snapcraft.io-pr-705.run.demo.haus/account/snaps/snap_name/listing
- Look at the `Private` section

# Screenshot

screenshot_2018-06-05 listing details for lukotron

### CODE REVIEW

**Comment by Greggless** [comment]
Something like this?

Moving it up into the first section gives it a little more context, and is a stop gap until we have the full meta data (or Admin tab) designed.

Using a radio menu is a little clearer about the binary state ( Public / Private)

Copy reads:
> ⚪️ **Private** _Snap is hidden in stores and only accessible by the publisher and collaborators_

image

**Comment by Greggless** [comment]
@Lukewh could we stick a `margin--top` to the second radio? Then +1!

**Comment by therealjuan** [comment]
Can you add a little bit more spacing between the privacy notice and the radio button?

**Comment by therealjuan** [comment]
Forget about my last comment :)

**Pull request merged**
