### PR TITLE
Icon to react component

### PR DESCRIPTION
**Pull request by Lukewh**
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1704
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1766

## QA
- Pull the branch
- `./run`
- Visit http://0.0.0.0:8004/<snap_name>/listing
- Drag and upload some files to use as an icon
- Delete the icon
- Click the icon to edit and upload a new icon
- Save a few times
- Revert
- etc.
- Ensure the screenshots still work as expected

### CODE REVIEW

**Comment by hughesjordan** [comment]
@Lukewh not sure if these are related to this PR but I'll mention anyway:

- When I add an icon that is above the file size limit, then add an image that is within the error message does not disappear.
- When I don't have an icon, upload one, then delete. The revert & save buttons are still enabled

And then other than this, it works:
- Lost the border since you updated
Screenshot 2019-04-05 at 12 08 37 pm

**Comment by bartaz** [comment]
@hughesjordan If snap has categories the 'Revert' button may be the same case as noticed with screenshots before (unrelated to this PR): https://github.com/canonical-websites/snapcraft.io/issues/1776

**Comment by bartaz** [comment]
I know there is little space in icon 'drop' area, but it would be nice if it at least said 'Drop' for a better hint (and consistency with screenshots).

**Comment by Lukewh** [comment]
> I know there is little space in icon 'drop' area, but it would be nice if it at least said 'Drop' for a better hint (and consistency with screenshots).

Updated for you @bartaz <3

**Pull request merged**
