### PR TITLE
Set the 'theme-color' to match the global nav

### PR DESCRIPTION
**Pull request by Lukewh**
Match the browser chrome and status bar to the global nav colour for seamlessness.

## QA

- Pull the branch
- `./run`
- Visit `{your-laptop-ip}:8004` on a mobile device (or visit the demo)
- See that the browser chrome and status backgrounds match the global nav

Before:
photo_2018-11-13_10-18-14

After:
photo_2018-11-13_10-18-21

### CODE REVIEW

**Comment by bartaz** [comment]
This makes 'Canonical' global header a bit too connected to browser chrome I think. Maybe using navigation header background would work better?

**Comment by Lukewh** [comment]
@bartaz I guess that's a design choice. Do we want the chrome to be seamless, or is it more important for the chrome to be 'on-brand' @lyubomir-popov @therealjuan

**Comment by therealjuan** [comment]
I am inclined to leave the browser to be white as that is the current chrome look and feel

**Comment by bartaz** [comment]
Are there any good examples of this theme colour use? I see it used by facebook, but didn't find any other good example. I feel like it fits more into a mobile web-app experience than the website.

**Comment by Lukewh** [comment]
https:///wwww.ubuntu.com does it, but uses the orange

**Pull request closed without merging**
