### PR TITLE
Surface non-stable snaps in search

### PR DESCRIPTION
**Pull request by Lukewh**
# Done

- Enables the `wide` `scope` on the search endpoint
- Hides the install button and associated overlay if there is not a stable version

# QA

- Pull the branch
- `./run`
- Visit http://0.0.0.0:8004/store
- Search for `hello-roadmr`
- You should get many more results than https://snapcraft.io/search?category=&q=hello-roadmr
- Click on `hello-roadmr-comm4`
- You should not have the install button in the header and clicking 'all versions' should only have 1 tab

### CODE REVIEW

**Comment by Greggless** [comment]
Is the UI/UX for this void as the behaviour will be different taking into consideration the new channel map updates? 

There's an interesting issue happening now; we 'special-cased' Node to display **`10/stable`** by default. Now that the `wide==` parameter has been brought in, Node's page defaults to the nightly build. Do we still need to 'special-case' Node?

We also need to change the publisher pages a little, but that's probably for another PR
image

**Comment by matthewpaulthomas** [comment]
👍

> Is the UI/UX for this void as the behaviour will be different taking into consideration the new channel map updates?

As far as I can see, this change alters only the “Install” button. The channel map appears when you click the “All versions” button, which is unaffected.

> Now that the `wide==` parameter has been brought in, Node's page defaults to the nightly build.

I don’t see this behavior, because I see #891 instead. (Initially I thought that bug was node-specific.)

**Comment by Greggless** [comment]
> As far as I can see, this change alters only the “Install” button. The channel map appears when you click the “All versions” button, which is unaffected.

I was thinking more along the lines of when [these changes](https://github.com/canonical-websites/snapcraft.io/issues/731) come in. I'm not sure what it's final form is, but it might be worth considering the affect non-stable snaps have

**Comment by bartaz** [comment]
Code looks good. But I'm not sure how `node` should work now. We have some custom code for it that was meant to make it default to `10` track (which has stable). This seems to be messing it up a bit by showing empty channel in default install instructions.

Juans PR done separately (https://github.com/canonical-websites/snapcraft.io/pull/893) 'fixes' it, but is just removes channel from install instructions and this is wrong for node which should show install instructions from `10/stable`.

**Comment by bartaz** [comment]
So (after fixing conflict and merging master) there is a small issue with node install instructions:

screen shot 2018-07-16 at 15 40 07

Channel was removed from install instructions and for `node` (that is a special case for not having stable in latest track) install instructions are wrong. But we may want to fix it separately.

**Pull request merged**
