### PR TITLE
Upgrade to ./run with proxy support

### PR DESCRIPTION
**Pull request by nottrobin**
**Please review https://github.com/canonical-webteam/generator-canonical-webteam/pull/38 at the same time**

This adds the new ./run script here: https://github.com/canonical-webteam/generator-canonical-webteam/pull/38 (review please)

The proof that the proxying part of this works is here: https://jenkins.canonical.com/webteam/job/snapcraft.io-deploy-to-staging-k8s/17/console

But to QA it locally:

``` bash
./run help
./run
./run clean
./run build
etc.
```

### CODE REVIEW

**Comment by WillMoggridge** [comment]
This and the related generator PR look good and work fine except that the first run after every `./run clean` results in:

```
16:45:58 ➜   ./run
groupadd: GID '1000' already exists

```
Docker version 17.06.0-ce
Bash version: 4.4.7

**Comment by nottrobin** [comment]
@WillMoggridge updated this as per the updates to the [./run PR](https://github.com/canonical-webteam/generator-canonical-webteam/pull/38#issuecomment-331640998). Let me know if you still get the error.

**Comment by grahambancroft** [comment]
@nottrobin I get this after a clean:

```
Graham-4:snapcraft.io grahambancroft$ ./run
groupadd: GID '20' already exists

```

**Comment by nottrobin** [comment]
@WillMoggridge, @caldav, @grahambancroft I believe this should be fixed now. Could you please test it again?

**Comment by caldav** [comment]
I concur with Travis:
    $ ./run
    Unable to find image 'canonicalwebteam/dev:v1.0.0' locally
    docker: Error response from daemon: manifest for canonicalwebteam/dev:v1.0.0 not found.
    See 'docker run --help'.

**Comment by nottrobin** [comment]
@caldav yes you tested it at exactly the wrong time :) sorry. Check again in 10 mins or so.

**Comment by caldav** [comment]
Works well for me now!

**Pull request merged**
