### PR TITLE
Better spacing for owner notification

### PR DESCRIPTION
**Pull request by Lukewh**
Fixes https://github.com/canonicalltd/snap-squad/issues/950

## QA

- Pull the branch
- `./run`
- Visit http://0.0.0.0/your-snap
- Make sure the notification at the top has correct spacing

### CODE REVIEW

**Comment by bartaz** [comment]
@hughesjordan @therealjuan 

How about if we move the notification to the top?
So we will not need to override any styling just to avoid conflicts with heading spacing.

Screenshot 2019-03-29 at 10 54 39

**Comment by therealjuan** [comment]
LGTM!

**Comment by hughesjordan** [comment]
👍🏻

**Comment by bartaz** [comment]
@therealjuan You approve what's in this PR or moving it up that I proposed (but is not implemented)? :)

**Comment by therealjuan** [comment]
I approved too early to realise that you didn't committed any change at all :)

**Comment by Lukewh** [comment]
How come this got closed?

**Comment by bartaz** [comment]
Was fixed by https://github.com/canonical-websites/snapcraft.io/pull/1760.

It should have been closed with a comment for context.

**Pull request closed without merging**
