### PR TITLE
Add build.snapcraft.io homepage to snapcraft.io/build

### PR DESCRIPTION
**Pull request by Lukewh**
# Done

Fixes https://github.com/canonical-websites/snapcraft.io/issues/919

- Added the content in a more familiar vanilla style

# QA

- Pull the branch
- `./run`
- Visit http://0.0.0.0:8004/build
- Compare the page to https://build.snapcraft.io

### CODE REVIEW

**Comment by therealjuan** [comment]
Probably the only comment I have will be to update the icons on the quotes:

**Comment by matthewpaulthomas** [comment]
If I go to [the current Build page](https://build.snapcraft.io/), choose “Set up in minutes”, and auth to GitHub, I end up on a page where the header has exactly the same items in the same positions with the same font size as before. The only change is a deliberate one: showing that I’m now signed in.

But if I go to [the demo Build page](http://snapcraft.io-pr-957.run.demo.haus/build) and choose “Set up in minutes”, I end up on a page where the header has some items the same, some different, all of them in a different position, and all in a smaller font.

#921 requests to “Update build.snapcraft.io header to match snapcraft.io”. But doing that would fix the header on this page automatically. So, what’s the point of reimplementing this page? What’s the point of having one “Build” page on snapcraft.io, while all the other “Build” pages remain on build.snapcraft.io until it’s retired (at which point this page will be redundant anyway)?

(This might be easier to understand if #919 had a description. It’s linked to [snap-squad#640](https://github.com/CanonicalLtd/snap-squad/issues/640) which says “there will be no need to maintain 2 different headers and footers”, but the existence of #921 suggests that isn’t true.)

A separate problem is that if I return to this new Build page after signing in, it ignores the fact that I am signed in. Instead of saying “Hi Matthew Thomas, let’s take a look at your repos”, it invites me to “set up” as if I haven’t already done that (incidentally making [build.snapcraft.io#1083](https://github.com/canonical-websites/build.snapcraft.io/issues/1083) worse), and there’s no longer any “Sign in with GitHub” link. We snapcraft.io developers know that the link and the button do the same thing under the hood. But I don’t think it would be obvious to users that they should click a “set up” button just to sign in.

**Comment by therealjuan** [comment]
> > If I go to the current Build page, choose “Set up in minutes”, and auth to GitHub, I end up on a page where the header has exactly the same items in the same positions with the same font size as before. The only change is a deliberate one: showing that I’m now signed in.
> 
> But if I go to the demo Build page and choose “Set up in minutes”, I end up on a page where the header has some items the same, some different, all of them in a different position, and all in a smaller font.
> 
> #921 requests to “Update build.snapcraft.io header to match snapcraft.io”. But doing that would fix the header on this page automatically. So, what’s the point of reimplementing this page? What’s the point of having one “Build” page on snapcraft.io, while all the other “Build” pages remain on build.snapcraft.io until it’s retired (at which point this page will be redundant anyway)?
> 
> (This might be easier to understand if #919 had a description. It’s linked to snap-squad#640 which says “there will be no need to maintain 2 different headers and footers”, but the existence of #921 suggests that isn’t true.)

The point is to have a similar CSS and JS being used on both places so if we update to a newer version of Vanilla the change does not need to be implemented in 2 different codebases. The problem with the header is why #921 exists, then we will fix the header using this same PR and we will have a look at the redirects so we can implement **the separate problem**.

Just give us some time and finish some briefs. Capicci? ;)

**Comment by bartaz** [comment]
As long as BSI is separate project with separate codebase there will be always two codebases to update for header/footer consistency as long as we insist on BSI having the same header as snapcraft.io.

Especially that BSI uses GH as main authentication and it will not be an easy task to have it work with Store/snapcraft.io sign in and GH at the same time.

BSI doesn't even use Vanilla fully, only some specific components which makes the updates even harder and it's still on Vanilla 1.6.4 because of that. Before we migrate BSI to Vanilla 1.7 (or 1.8 now) it will be quite hard to maintain consistency.

**Comment by lyubomir-popov** [comment]
@therealjuan attaching resized logos


[Archive.zip](https://github.com/canonical-websites/snapcraft.io/files/2256729/Archive.zip)

**Comment by therealjuan** [comment]
Thanks @lyubomir-popov will upload to the assets site

**Comment by therealjuan** [comment]
There are some redirect issues but I guess this PR only covers homepage. LGTM otherwise 👍

**Comment by Lukewh** [comment]
@therealjuan I think we should release BSI and this stuff at the same time next week. When all issues in the epic are :+1:'d

**Comment by therealjuan** [comment]
That's what I was imagining because it is 1/3 of the overall task 👍

**Pull request merged**
