### PR TITLE
Improved homepage logos

### PR DESCRIPTION
**Pull request by Lukewh**
Fixes https://github.com/canonical-websites/snapcraft.io/issues/831

# QA

- Pull this branch
- `./run`
- Visit http://0.0.0.0:8004/
- Make sure the top publisher logos look correct

### CODE REVIEW

**Comment by Lukewh** [comment]
Updated with [Lyubo approved] logos @lyubomir-popov

**Comment by lyubomir-popov** [comment]
Thanks @Lukewh, looks good on your machine, giving a plus one.

**Comment by matthewpaulthomas** [comment]
Confirmed less blurry. (And as a bonus, the Amazon logo is lined up better with the others.)

**Comment by Lukewh** [comment]
@matthewpaulthomas it's always good to over deliver, especially when it comes to amazon logo alignment.

Thanks all.

**Pull request merged**
