### PR TITLE
Add link to listing page on own snaps

### PR DESCRIPTION
**Pull request by tbille**
# Summary

Add link to listing page if the snap belongs to you

# QA

- `./run`
- login
- Go on a snap that belongs to you
- Check if you have the link to the listing page under the title like this

image

- Go on  a snap that doen't belongs to you
- This link should exist

### CODE REVIEW

**Comment by therealjuan** [comment]
Great! but might be better to swap this content with the publisher name. i.e `You own this snap. [Edit snap information]`

**Comment by tbille** [comment]
@therealjuan like this?

image

**Comment by bartaz** [comment]
@therealjuan I'm not sure if removing "by [publisher]" is good. Because as publisher you will have no way to see how details page looks (with you publisher name) for other people when you are logged in. This may not seem much (just publisher name), but maybe they would notice that they want to change their displayed name or something.

So I'd be for adding the [Edit] link, but not removing any information from the page.

**Comment by tbille** [comment]
@bartaz @therealjuan 

image

**Pull request merged**
