### PR TITLE
Updated homepage quote

### PR DESCRIPTION
**Pull request by Lukewh**
# Done

Fixes https://github.com/CanonicalLtd/snapcraft-design/issues/324

- Changed 3rd quote on the homepage

# QA

- Pull this branch
- `./run`
- Visit the homepage

**or**

- Visit [the demo](http://snapcraft.io-pr-530.run.demo.haus/)

- Ensure the quote is changed

### CODE REVIEW

**Comment by tbille** [comment]
Small comment, the quotes look like a pyramid
screenshot-2018-4-18 snapcraft - snaps are universal linux packages

**Comment by Greggless** [comment]
@evandandrea what do you think about reducing Jeff Dickey's quote?:
> ~~We had been facing issues with packaging problems for years...snaps seemed it would make my life a lot easier.~~ The auto-updating feature is huge and one that we haven’t seen elsewhere. Due to the nature of our platform, we release updates more than daily which admittedly can be annoying for our users to constantly update. Therefore, having them done seamlessly in the background makes life for our users so much easier. It’s great to see snaps as the first serious attempt to try and unify the community.

It shouldn't be a blocker, though

**Comment by Lukewh** [comment]
Doing that @Greggless would mean the title would be the same as the first sentence, which might be a bit odd?

**Comment by Lukewh** [comment]
@tbille can you approve the code with the +1'ing please?

**Comment by Greggless** [comment]
Ah, didm't even clock that. How about:

>### The auto-updating feature is huge
>Due to the nature of our platform, we release updates more than daily which admittedly can be annoying for our users to constantly update. Therefore, having them done seamlessly in the background makes life for our users so much easier. It’s great to see snaps as the first serious attempt to try and unify the community.

### Word count:
- Quote 1: 56
- Qutoe 2: 72
- Quote 3: 57

**Pull request merged**
