### PR TITLE
Add ./run script

### PR DESCRIPTION
**Pull request by nottrobin**
In this case, the `./run` script is a bit more custom than usual as it needs to pull down docs as well.

It tries to do this intelligently, and only refresh them when something changes.

When this is merged, the Jenkins job will need to be updated to run `./run build` instead of `./import-docs`.

I picked port `8004` for this site, and mentioned it [in the practices repo](https://github.com/canonical-webteam/practices/pull/23/files).

I have also removed all JavaScript, as I don't think it's being used any more.

QA
--

You know the drill by now:

``` bash
./run clean
./run
./run test
./run watch
etc.
```

### CODE REVIEW

**Comment by nottrobin** [comment]
[Add ./run script](https://trello.com/c/Cj0JMxfO/3295-add-run-script)

**Comment by WillMoggridge** [comment]
Rather than modify the run file, it seems to make more sense to me to put it in the package.json build script. Could we do this instead?

**Comment by nottrobin** [comment]
Good point @WillMoggridge I agree that would be a better location for it.

This would move the running of those build tasks into the node image. Currently the build tasks are:

- Clone from GitHub
- Run `./update-docs-layout.py`

There would be workarounds for both. We could either include `git` in the node image, or pull down an archive with `curl`. And `update-docs-layout.py` would presumably be relatively easy to re-write in Python.

This question is also relevant to https://github.com/canonical-websites/docs.ubuntu.com/pull/72. In that case it's more difficult to move everything into the node image, as the building of docs relies heavily on [documentation-builder](https://github.com/canonical-webteam/documentation-builder). In that case, I think I'd rather wait until we solve https://github.com/canonical-websites/docs.ubuntu.com/issues/65, so I think we should just wait for that and then this issue will be solved a completely different way.

Similarly, when that happens, I hope we will also be moving Snapcraft docs to docs.ubuntu.com anyway, in the long run.

However, for now I'd rather push this work down the line and get this PR merged if that's okay?

**Comment by WillMoggridge** [comment]
Yeah sure, sounds good

**Pull request merged**
