### PR TITLE
Don't loop asciinema on details pages

### PR DESCRIPTION
**Pull request by Lukewh**
Fixes https://github.com/canonical-websites/snapcraft.io/issues/1763#event-2252195260

## QA
- Pull the branch
- `./run`
- Visit http://0.0.0.0:8004/<snap_with_asciinema>
- Watch the asciinema, see that it doesn't loop

### CODE REVIEW

**Comment by bartaz** [comment]
If we disable looping for asciinema, we should disable it for other videos as well for consistency.

**Comment by Lukewh** [comment]
> If we disable looping for asciinema, we should disable it for other videos as well for consistency.

It's a different beast from advocacy "as long as the videos still loop +1"

**Comment by bartaz** [comment]
> "as long as the videos still loop +1"

🤷‍♂️

**Comment by evandandrea** [comment]
>"as long as the videos still loop +1"

I can see the rationale for not looping asciinema (as demonstrated in #1763). You want to have the video end with some static text that you can look over. Normal videos, on the other hand, more typically demonstrate some graphical functionality and seeing it in a tight loop can be helpful.

**Comment by therealjuan** [comment]
UX+1 but created a new issue as youtube and asciinema should behave similarly as it can be confusing to have 2 video implementations acting differently. It is more useful to have graphical context looping but should be up to the visitor to decide if it wants to keep looping the video.

One potential benefit of stopping playback on the video is that users might want to scroll down and dig more on the given snap they are visiting. With auto-looping, this might means that users will skip looking at the rest of the page and just leave once they have seen the page a couple of times.

New issue: https://github.com/canonical-websites/snapcraft.io/issues/1801

**Pull request merged**
