### PR TITLE
Defend against snapcraft 'not being defined'

### PR DESCRIPTION
**Pull request by Lukewh**

### CODE REVIEW

**Comment by Greggless** [comment]
⚠️ `Dumb designer question` ⚠️

> What is this? @Lukewh

**Comment by bartaz** [comment]
It's an error from sentry.
Means that JavaScript didn't load properly and didn't run (so for example map was not shown on details page).

This PR means we will stop getting this error, but still JavaScript will not run.
We will just not know about it, because it will silently fail for user.

I'm not sure if it's good approach. Even though we cannot have any good way to debug it (maybe user blocks JavaScript or it fails to load for some other reason) - we should try to investigate why it maybe happening.

**Comment by tbille** [comment]
This is a hack, @bartaz found out where the problem comes from: we need to transpile our code. PR is on its way!

**Comment by Greggless** [comment]
Thanks for explaining! 

# :electron:

**Comment by Lukewh** [comment]
PR is here: https://github.com/canonical-websites/snapcraft.io/pull/370

**Pull request closed without merging**
