### PR TITLE
Make navigation full width

### PR DESCRIPTION
**Pull request by Lukewh**
Partially fixes https://github.com/canonical-websites/snapcraft.io/issues/592

build.snapcraft.io will be sorted by https://github.com/CanonicalLtd/snap-squad/issues/640

# QA

- Pull the branch
- `./run`
- Click around (within this codebase)
- The navigation should be full width

### CODE REVIEW

**Comment by therealjuan** [comment]
All well and good but if you add `"` and large words to the term...

image

To solve this we can ... 

- **(a)** strip the quotes or 
- **(b)** leave the search as is and have a different style for the search term, as well as use [ellipsis](https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/) to avoid the layout being broken

**Comment by Greggless** [comment]
It would be nice to differentiate the system text from the query text. If quotes are a no-go we can use Ubuntu regular for the query text. But that might look kinda weird and oddly sized with it being a `H2`. So I'd suggest using `H3` (and reflect changes to other pages of a similar template). 

Ellipsis are cool, though 😄

**Comment by Greggless** [comment]
GTML :shipit:

**Comment by lyubomir-popov** [comment]
@Greggless I believe the design +1 should be applied by someone on the visual design side of things, rather than the UX side. Maybe the label needs renaming to avoid confusion?

**Comment by Greggless** [comment]
Ah, apologies @lyubomir-popov. That was actually supposed to be a `UX+1` rather than a `Design +1`

**Pull request merged**
