### PR TITLE
Improve request name view

### LINKED ISSUE #678: Reserve name template UX improvements
Issue to address feedback from: https://github.com/canonical-websites/snapcraft.io/pull/670

> Relatedly, you can change the “Snap name” value to a name that isn’t taken. If you do that, the rest of the form still assumes that you’re requesting a reserved name, when you no longer are.
>
>A minimal way to fix this would be for the “Request reserved name” form not to contain a “Snap name” field at all. (And since that was the only place the name was disclosed, the intro text would need changing to remind you what name you’re trying to request.)

#### Tasks:
- [x] Remove 'Snap name' field
- [x] Use the `SNAP_NAME` that is being requested in the form title
- [x] Change intro text
- [x] Remove privacy and store selection (user already set this on the previous page)

_It'll be laid out a little like this:_

<hr>

_Title:_
## Request the name '<SNAP_NAME>'

_Intro:_
#### Supporting comment
`textfield`

                                                     `Cancel`          **`[Request name]`**
<hr>

### PR DESCRIPTION
**Pull request by tbille**
# Summary

Fixes #678 
- Improve UX for request name

# QA

- `./run`
- http://127.0.0.1:5000/account/register-name
- Register already existing snap
- Like new page :)

### CODE REVIEW

**Comment by Lukewh** [comment]
@tbille I think you can:

- Remove the text 'Please provide a reason why you would like ownership of the snap' just above the textarea as it's just a repeat of the subtitle.
- Change the subtitle from a `h2` to a `p` and remove the class
- add the `u-no-margin--top` class to the `form` element

**Comment by Lukewh** [comment]
Also on the register page:

- Change the `h2` to a `p`
- Add `u-no-margin--top` class to the `form` element
- Move the `p-form-validation` elements to be siblings within the first `row col-8` (then remove the extra row)
- Add `u-no-margin--top` to the rows with the `hr` and buttons in

**Comment by Greggless** [comment]
⚠️ **Firefox** has already been registered by another publisher. You can request a transfer of ownership, which will be reviewed by the store administrators or [register a different name](https://snapcraft.io/account/register-name).

<hr>

Please provide a reason as to why you would like to own this name:

<hr>

**Comment by Greggless** [comment]
# Looks Get This Me  :shipit:

**Pull request merged**
