### PR TITLE
Blog series

### PR DESCRIPTION
**Pull request by Lukewh**
Fixes https://github.com/canonical-websites/snapcraft.io/issues/911

# QA

- Pull the branch
- `./run`
- Visit http://0.0.0.0:8004/blog/your-first-robot-a-beginners-guide-to-ros-and-ubuntu-core-1-5
- See a list of the other blogs in the series on the right-hand side
- Visit http://0.0.0.0:8004/vscode and ensure the related blog posts appear there still

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
@Lukewh I have a couple of suggestions:

Currently:

image



After applied alterations:

image


Most importantly, things don’t look properly grouped. The title is in a strip of its own, with a marketing-y background, ansd the related articles appear almost as text accompanying  the image

So I got rid of the top banner, and added an extra column of white space in the aside
I would also wrap the image in a p-strip is-shallow
(not done above). Images from cms’s often get wrapped in <p>’s and we have a rule that brings p+p closer together - so the space between image and paragraph is too small.

**Comment by lyubomir-popov** [comment]
@Lukewh I've added a -1 as I'm not aware of any ongoing discussions, and am assessing this as is. If there are reasons we want this out quickly, and have plans to iterate on it later, pls let me know and I'll add a plus one as the above issues are in no way critical.

**Comment by lyubomir-popov** [comment]
@Lukewh @bartaz Also, there seem to be leftover overrides from before Vanilla 1.7/8:

image

**Comment by matthewpaulthomas** [comment]
- The list contains the current post, so “Other posts” is incorrect, sorry, –1 for that. How about just “In this series”? (That would also keep the heading to one line.)

- Linking the post that you’re already on (besides the usual self-link risk of no-op clicking) makes it difficult to see where you are in the series. It would be better as just plain text, or even bold.

- Seeing where you are in the series makes it good that the links are visible at the top of the page. Besides that, though, their main use is to navigate to the next post once you’ve finished this one, right? And for that, they should be visible at the bottom of the page too, so you don’t need to scroll all the way back to the top when you’ve finished. (And so you don’t forget that the links were there at all.) Since the links have a column to themselves, this can be achieved by making them sticky (or at least semi-sticky, scrolling only if the list is taller than the viewport).

**Comment by Lukewh** [comment]
Thanks @matthewpaulthomas, updated if you could take another look. The demo should update soon.

**Comment by matthewpaulthomas** [comment]
Excellent, thanks @Lukewh.

One remaining glitch: If the list is taller than the viewport, you need to scroll all the way to the bottom of the page (well, the bottom of the `<section id="maincontent">`) before you get to see the last item in the list. But that’s quite unlikely, and I guess it’s hard to fix (you’d need to switch between making the top or bottom sticky depending on the scroll direction), so it needn’t block this change.

**Pull request merged**
